---
- name: Deploy HealSphere App using Docker Compose
  hosts: localhost
  become: false

  vars:
  project_path: "{{ lookup('env', 'WORKSPACE') }}"

  tasks:
    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Pull Latest Images
      shell: docker compose pull
      args:
        chdir: "{{ project_path }}"

    - name: Recreate and Start Containers
      shell: docker compose up -d --remove-orphans
      args:
        chdir: "{{ project_path }}"
