---
- name: Deploy HealSphere App using Docker Compose
  hosts: localhost
  become: true  # Ensure you have the necessary privileges to stop the MySQL service

  vars:
    project_path: "{{ lookup('env', 'WORKSPACE') }}"

  tasks:
    - name: Stop MySQL service if running
      ansible.builtin.service:
        name: mysql
        state: stopped
      ignore_errors: yes  # Continue even if MySQL is not running

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pull Latest Docker Images
      shell: docker compose pull
      args:
        chdir: "{{ project_path }}"  # Use project_path dynamically

    - name: Recreate and Start Containers
      shell: docker compose up -d --remove-orphans
      args:
        chdir: "{{ project_path }}"  # Use project_path dynamically
